// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvbeqID5i_ZD4jfWGABavWJFV66Ii-RKA',
    appId: '1:69644684545:web:3d4010e0706502f5f0df00',
    messagingSenderId: '69644684545',
    projectId: 'mobile-eeda2',
    authDomain: 'mobile-eeda2.firebaseapp.com',
    storageBucket: 'mobile-eeda2.firebasestorage.app',
    measurementId: 'G-3LCEDE427J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdNeRnyMJnwZrD3jCXVCd5YJ7jkEMzvI',
    appId: '1:69644684545:android:07bb246986802b39f0df00',
    messagingSenderId: '69644684545',
    projectId: 'mobile-eeda2',
    storageBucket: 'mobile-eeda2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfBXVhXtlEMNSvkIC90-lBEYgKCn30Rk8',
    appId: '1:69644684545:ios:090bc84fcdd52766f0df00',
    messagingSenderId: '69644684545',
    projectId: 'mobile-eeda2',
    storageBucket: 'mobile-eeda2.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfBXVhXtlEMNSvkIC90-lBEYgKCn30Rk8',
    appId: '1:69644684545:ios:090bc84fcdd52766f0df00',
    messagingSenderId: '69644684545',
    projectId: 'mobile-eeda2',
    storageBucket: 'mobile-eeda2.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvbeqID5i_ZD4jfWGABavWJFV66Ii-RKA',
    appId: '1:69644684545:web:c59000d0fdc3171df0df00',
    messagingSenderId: '69644684545',
    projectId: 'mobile-eeda2',
    authDomain: 'mobile-eeda2.firebaseapp.com',
    storageBucket: 'mobile-eeda2.firebasestorage.app',
    measurementId: 'G-VDZ8TBJ6PF',
  );
}
